### ISSUE TITLE
Failure for a degeneracy problem

### ISSUE THREAD

**Issue by devinInOttawa** [LKolonias/Simplex#1]
min z = -3 * x_1 - 9 * x_2
s.t.
-x_1 -4 * x_2 >= -8
-x_1 -2 * x_2 >= -4
x_1 >= 0
x_2 >= 0

correct solution [0 2]
currently, the program gave solution [2 0]

**Comment by LKolonias** [comment]
There was an indexing problem upon construction of the solution vector which is now fixed. Thank you very much for noticing.
